# https://ashishnoob.medium.com/creating-a-mysql-instance-with-docker-compose-92e749c43611
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Create named volume called mysql_data in docker

volumes:
  mysql_data: