# https://ashishnoob.medium.com/creating-a-mysql-instance-with-docker-compose-92e749c43611
# SELECT current_user; to verify user name
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: orcun
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Create named volume called mysql_data in docker

volumes:
  mysql_data: