#  https://medium.com/@raveeshaamarawickrama200/stored-procedures-in-mysql-98544b870766
version: '3.9'
services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    # environment variables are not a list
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: userdb
      # root can log in from every host
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL script



