# https://medium.com/@manojkumar_41904/understanding-kubernetes-service-dns-a-deep-dive-7bf68b2baa63
# https://medium.com/@ninapepite/stop-use-kubernetes-as-a-docker-314d307d6dfb
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql-label  # Label for easy undeploy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-label  # Label for easy undeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: glpi
            - name: MYSQL_USER
              value: glpi
            - name: MYSQL_PASSWORD
              value: glpi
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "60" ]
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-label  # Label for easy undeploy
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306