# https://medium.com/@manojkumar_41904/understanding-kubernetes-service-dns-a-deep-dive-7bf68b2baa63
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-label  # Label for easy undeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-label  # Label for easy undeploy
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306